
package visualizzazione_dipendente;

import beans.Dipendente;
import beans.Impresa;
import dao.DipendenteDAO;
import dao.ImpresaDAO;
import java.util.List;
import javax.swing.JOptionPane;


public class SchermataRicercaDipendente extends javax.swing.JFrame {
        private void compilaIlModulo(){
        ImpresaDAO idao = new ImpresaDAO();
        List<Impresa> lista = idao.getImpresa("");
        for (Impresa i : lista){
            impresaD.addItem(i);
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataRicercaDipendente.class.getName());

    /**
     * Creates new form SchermataRicercaDipendente
     */
    public SchermataRicercaDipendente() {
        initComponents();
        this.setTitle("Cerca un dipendente");
        compilaIlModulo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cercaId = new javax.swing.JButton();
        idTr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        data = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nomeTr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        impresaD = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        idD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(6, 158, 120));
        jPanel1.setForeground(new java.awt.Color(6, 158, 120));

        jLabel1.setBackground(new java.awt.Color(244, 244, 244));
        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 244, 244));
        jLabel1.setText("Cerca uno dipendente tramite il suo ID:");

        cercaId.setText("Cerca con ID");
        cercaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaIdActionPerformed(evt);
            }
        });

        idTr.setForeground(new java.awt.Color(24, 24, 24));
        idTr.setText(" ");
        idTr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTrActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(244, 244, 244));
        jLabel2.setText("Nome:");

        jLabel3.setForeground(new java.awt.Color(244, 244, 244));
        jLabel3.setText("Data di ammissione:");

        nome.setEditable(false);
        nome.setText(" ");
        nome.setEnabled(false);
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        data.setEditable(false);
        data.setText(" ");
        data.setEnabled(false);

        jLabel4.setBackground(new java.awt.Color(244, 244, 244));
        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(244, 244, 244));
        jLabel4.setText("Cerca tramite il nome:");

        nomeTr.setText(" ");

        jButton1.setText("Cerca attraverso suo nome ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(244, 244, 244));
        jLabel5.setText("Impresa:");

        impresaD.setEnabled(false);

        jLabel6.setForeground(new java.awt.Color(244, 244, 244));
        jLabel6.setText("ID:");

        idD.setText(" ");
        idD.setEnabled(false);
        idD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(idD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(idTr, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cercaId))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeTr)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome)
                            .addComponent(impresaD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cercaId)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(impresaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(idD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cercaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaIdActionPerformed
        DipendenteDAO ddao = new DipendenteDAO();
        String idS = idTr.getText().strip();
        int idCorretto = Integer.parseInt(idS);
        Dipendente d = ddao.getDipendente(idCorretto);

        if(d == null){
            JOptionPane.showMessageDialog(null, "Dipendente non trovato.");
            idTr.setText("");
        }else{
            try {
                idD.setText(String.valueOf(d.getId()));
                nome.setText(d.getNome());
                data.setText(d.getAmmissione().toString());
                impresaD.setSelectedItem(d.getImpresa());
            }catch(Exception e){
                System.out.println("Errore trovato: "+ e.getMessage());
            }
            
            idTr.setText("");
        }

    }//GEN-LAST:event_cercaIdActionPerformed

    private void idTrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTrActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ImpresaDAO idao = new ImpresaDAO();
        Impresa i = new Impresa();
        try{
            String nomeAlt = nomeTr.getText().strip();

            i = idao.getImpresaNome(nomeAlt);
            if(i==null){
                JOptionPane.showMessageDialog(null,"Impresa non trovata.");
            }else{
                int idNuovo = i.getId();
                String nomeNuovo = i.getNomedellimpresa();
                String areaNuova = i.getAreadicompetenza().toString();
                String idTxt = Integer.toString(idNuovo);

                
                idTr.setText(idTxt);
                nome.setText(nomeNuovo);
                data.setText(areaNuova);
                impresaD.setSelectedItem(i);
                
            }

        }catch(Exception e){

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermataRicercaDipendente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cercaId;
    private javax.swing.JTextField data;
    private javax.swing.JTextField idD;
    private javax.swing.JTextField idTr;
    private javax.swing.JComboBox<Impresa> impresaD;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomeTr;
    // End of variables declaration//GEN-END:variables
}
